{% set version = "0.3.21" %}

package:
  name: retrolab
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/retrolab/retrolab-{{ version }}.tar.gz
  sha256: 06df283b25ba52678d679b2a64d925ece3e14e38dff1094d973fae2af15ca0a6

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - jupyter-retro = retrolab.app:main

requirements:
  host:
    - jupyter-packaging >=0.10,<1
    - pip
    - python {{ python_min }}

  run:
    - nbclassic >=0.2,<1
    - jupyterlab >=3.4.0,<4
    - jupyterlab_server >=2.3,<3
    - jupyter_server >=1.4,<2
    - python >={{ python_min }}
    - tornado >=6.1.0

test:
  imports:
    - retrolab
  commands:
    - pip check
    - jupyter retro --help
    - jupyter labextension list
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jupyterlab/retrolab
  summary: JupyterLab distribution with a retro look and feel
  license: BSD-3-Clause
  license_file: LICENSE
  description: JupyterLab distribution with a retro look and feel
  dev_url: https://github.com/jupyterlab/retrolab

extra:
  recipe-maintainers:
    - jtpio
    - blink1073
    - afshin
    - bollwyvl
