{% set name = "retrolab" %}
{% set version = "0.2.1" %}
{% set sha256 = "943fb6d3e6358f89b59c6ca7f6630be1c785394749d02982cfde91a641abd0df" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - jupyter-retro = retrolab.app:main

requirements:
  host:
    - jupyter-packaging >=0.7.9,<0.8.0
    - pip
    - python >=3.6

  run:
    - nbclassic >=0.2,<1
    - jupyterlab >=3.0.9,<4
    - jupyterlab_server >=2.3,<3
    - jupyter_server >=1.4,<2
    - python >=3.6
    - tornado >=6.1

test:
  imports:
    - retrolab
  commands:
    - pip check
    - jupyter retro --help
    - jupyter labextension list
  requires:
    - pip

about:
  home: https://github.com/jupyterlab/retrolab
  summary: JupyterLab distribution with a retro look and feel 
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    JupyterLab distribution with a retro look and feel
  dev_url: https://github.com/jupyterlab/retrolab

extra:
  recipe-maintainers:
    - jtpio
    - blink1073
    - afshin
    - Zsailer
