{% set version = "0.3.17" %}

package:
  name: retrolab
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/retrolab/retrolab-{{ version }}.tar.gz
  sha256: 349c1d6713b7900c7b4d7d368c2ff7243950102d2faabfa5d447c0e1e6b39fb2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - jupyter-retro = retrolab.app:main

requirements:
  host:
    - jupyter-packaging >=0.10,<1
    - pip
    - python >=3.6

  run:
    - nbclassic >=0.2,<1
    - jupyterlab >=3.2.0,<4
    - jupyterlab_server >=2.3,<3
    - jupyter_server >=1.4,<2
    - python >=3.6
    - tornado >=6.1

test:
  imports:
    - retrolab
  commands:
    - pip check
    - jupyter retro --help
    - jupyter labextension list
  requires:
    - pip

about:
  home: https://github.com/jupyterlab/retrolab
  summary: JupyterLab distribution with a retro look and feel
  license: BSD-3-Clause
  license_file: LICENSE
  description: JupyterLab distribution with a retro look and feel
  dev_url: https://github.com/jupyterlab/retrolab

extra:
  recipe-maintainers:
    - jtpio
    - blink1073
    - afshin
    - bollwyvl
