{% set name = "retrolab" %}
{% set version = "0.3.0" %}
{% set sha256 = "6265e4dc4db103d8073d3dbd9f24f85183479e4387608e7498c7e2b6464a356a" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - jupyter-retro = retrolab.app:main

requirements:
  host:
    - jupyter-packaging >=0.10,<1
    - pip
    - python >=3.6

  run:
    - nbclassic >=0.2,<1
    - jupyterlab >=3.1.0,<4
    - jupyterlab_server >=2.3,<3
    - jupyter_server >=1.4,<2
    - python >=3.6
    - tornado >=6.1

test:
  imports:
    - retrolab
  commands:
    - pip check
    - jupyter retro --help
    - jupyter labextension list
  requires:
    - pip

about:
  home: https://github.com/jupyterlab/retrolab
  summary: JupyterLab distribution with a retro look and feel
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    JupyterLab distribution with a retro look and feel
  dev_url: https://github.com/jupyterlab/retrolab

extra:
  recipe-maintainers:
    - jtpio
    - blink1073
    - afshin
